### ISSUE TITLE
Require accept/decline/waitlist notification?

### ISSUE THREAD

**Issue by vmbrasseur** [builderscon/builderscon#24]
Per [this section](https://github.com/builderscon/builderscon/blob/master/HOWTO-CFP.md#feedback).

One perennial complaint I hear from people who submit talks to conferences is that they never hear back. The programme will be announced but some speakers never hear whether their talks were declined. Sometimes it's because the conference is holding these talks in reserve in case of cancelations, but often it's just because the conference organizers are bad at communication. This lack of communication is lazy and disrespectful.

It would be great if Builderscon events could avoid this by requiring prompt and thorough communication of proposal status.

**Comment by lestrrat** [comment]
Is there specific wording that you are proposing/would like to see?

BTW, reserves! That's a new concept for me.

**Comment by vmbrasseur** [comment]
I hadn't gotten as far as wording but could whip something together in a PR if you'd like?

Yeah, "waitlisted" is a pretty common status I see. I don't always agree w/how it's used, but to each their own. 😁

**Comment by lestrrat** [comment]
Yeah, basically I know what you mean, but am not sure if I can quite guess what precise measures you wanted, so either a PR or just bullet list of the flow that you want to see, etc so I can come up with the wording would be nice

**Comment by vmbrasseur** [comment]
PR sent!

**Comment by lestrrat** [comment]
Oh I get it . I thought you were thinking of something more elaborate!

**Comment by lestrrat** [comment]
merged! thanks

**Comment by vmbrasseur** [comment]
❤️
