### ISSUE TITLE
欲しい: スポンサーのツボを突く資料作り

### ISSUE THREAD

**Issue by hasegawa-tomoki** [builderscon/builderscon#3]
スポンサープランを作って、さあ売るぞ！という時にどんなスポンサー資料があるとスポンサーのツボを突くのかが分かると嬉しい。

おそらく以下の様なことも関連する:
- （特に大企業の）企業内での検討プロセスがどうなっているか
  - 予算のタイミング
  - 検討にかかる時間
  - 金額によるプロセスの違い
- 資料はどういう人が見るものとして設計すべきか

**Comment by hasegawa-tomoki** [comment]
営業に行って聞かれたこと。
- そもそもどういうことをやるの？
- 何か唐突に発生したイベントという感じだけど何なの？
- 400枚とかチケット売れるの？***円とか高くない？
- どういう人が来るの？

**Comment by hasegawa-tomoki** [comment]
iOSDCでスポンサー集めをやってみて、当たり前だけど「1に求人2に求人3,4が無くて5に求人」みたいな状態だとわかった。
上記の様なことは大事だけど、「求人」に尽きるかなと。
なので、「スポンサーのツボを突くには、ほとんどのスポンサーは求人のことを第1に考えているということを認識すること」な気がします。

**Comment by lestrrat** [comment]
運営側でそれを理解するのは重要なんだけど、「求人」というのを矢面に出すと参加者が冷める傾向があると思うのですよね。文章にするのむずいなぁ〜

**Comment by hasegawa-tomoki** [comment]
そうですね。
スポンサー対応をする時に、「彼らは何が欲しいんだろう」と考えると「求人！」というのが根っこにはあるんだな、ぐらいのコメントでした。

（そうえいば、PHPカンファレンス福岡のスポンサーセッションはちゃんとテクニカルで好評でした。ああ、こういうセッションならスポンサーにもカンファレンスにも利益があるなあ、と。）

**Comment by lestrrat** [comment]
それ、できるんだけど、多分「これくらいのクォリティのものを求めています」というのを明文化するのが難しいだけだと思いますね。お願いするにあたってどういうふうにお互いの期待値を揃えるのか @hasegawa-tomoki さんが明文化にトライしてみてはいかがでしょう！そしたらbuildersconに追加できる :D

**Comment by hasegawa-tomoki** [comment]
スポンサーセッションの話ですよね。
今のところ、iOSDCではスポンサーセッションが無いのですが、builderscon / Powered by builderscon でやる場合は、明文化にトライしたいですね。
（今のドキュメントでも良い説明できていると思うけど。）

**Comment by lestrrat** [comment]
@hasegawa-tomoki そうそう＞スポンサーセッション
buildersconの今のドキュメントは「どうやってスポンサーセッションをやりたいというスポンサーにお引き取りいただくか」を主眼に書いているので、逆にどうやって高いクォリティのスポンサーセッションをやってもらうか、ってのはできるならあったほうがいいなぁ、と思った次第。

**Comment by hasegawa-tomoki** [comment]
そうですね。
やることになったら明文化にトライしましょう！
