### ISSUE TITLE
builderscon/Beacon 表記を統一する

### ISSUE THREAD

**Issue by lestrrat** [builderscon/builderscon#5]
Builders ConferenceってのがUKにあるのであえて「Beacon」ってのを使ったんだけど、buildersconで統一したほうがいいのかな？

**Comment by hasegawa-tomoki** [comment]
Beaconって、iBeacon的な一般用語としてのビーコンと同じスペルでググラビリティがちょっと心配、というのはありますねえ。

**Comment by januswel** [comment]
Beacon だとコンテクストがないとどの意味かわからない可能性はありますね。
builderscon に統一に一票です。

**Comment by nasa9084** [comment]
知名度をあげていくときにググラビリティって結構大事ですよね。あとはぱっと見でわかりやすい方がいいかもですね。
Beaconの方がゴロはいいですけど、、、
buildersconに統一で一票です。
